name: Github Actions

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta                                      #스텝의 이름
        id: docker_meta                                        #변수의 일부이며 나중에 output값으로 활용 가능
        uses: crazy-max/ghaction-docker-meta@v1                #사용할 동작
        with:                                                  #동작에 대한 input값 사용 선언
          images: wndudwns0028/flask-socket                    #이미지 이름 지정
          tag-semver: |                                        #이미지 이름 뒤에 들어갈 버전 정보
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub                               #스텝의 이름
        uses: docker/login-action@v1                           #사용할 동작
        with:                                                  #동작에 대한 input값 사용 선언
          username: ${{ secrets.DOCKERHUB_USERNAME }}          #Docker Hub의 사용자 ID
          password: ${{ secrets.DOCKERHUB_TOKEN }}             #Docker Hub에서 발급 받은 사용자 Token
      -
        name: Build and push                                   #스텝의 이름
        uses: docker/build-push-action@v2                      #사용할 동작
        with:                                                  #동작에 대한 input값 사용 선언
          context: .                                           #context
          file: ./Dockerfile                                   #빌드 시 사용할 Dockerfile의 위치 지정
          platforms: linux/amd64                               #이미지 등록 시 Platform 이름 지정
          push: true                                           #빌드 후 배포 여부 체크 
          tags: ${{ steps.docker_meta.outputs.tags }}          #빌드 시 위에서 지정한 태그를 사용하도록 지정
          labels: ${{ steps.docker_meta.outputs.labels }}      #빌드 시 위에서 지정한 태그를 사용하도록 지정
